language: python
cache: pip
dist: xenial
python:
  - "3.7"
services:
  - docker
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - sleep 10
  - psql -c 'create database buildly_api;' -U postgres
  - sudo touch /var/log/buildly.log
  - sudo chown travis /var/log/buildly.log
install:
  - cat requirements/base.txt | grep "^Django==\|^psycopg2" | xargs pip install
  - pip install -r requirements/ci.txt
script:
  - flake8
  - bandit -r . -ll
  - pytest --cache-clear
  - docker build -t $DOCKER_REPO .
env:
  global:
    ALLOWED_HOSTS: "*"
    API_URL: "/api/docs"
    CORS_ORIGIN_WHITELIST: "*"
    DATABASE_ENGINE: "postgresql"
    DATABASE_NAME: "buildly_api"
    DATABASE_USER: "postgres"
    DATABASE_PASSWORD: ""
    DATABASE_HOST: "localhost"
    DATABASE_PORT: "5432"
    DEFAULT_ORG: "Default Organization"
    DJANGO_SETTINGS_MODULE: "buildly.settings.production"
    SOCIAL_AUTH_GITHUB_REDIRECT_URL: "/complete/github"
    SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URL: "/complete/google-oauth2"
    SOCIAL_AUTH_MICROSOFT_GRAPH_REDIRECT_URL: "/complete/microsoft-graph"
    JWT_ISSUER: "buildly"
    JWT_PRIVATE_KEY_RSA_BUILDLY: $'-----BEGIN RSA PRIVATE KEY-----\nMIIBOwIBAAJBALFc9NFZaOaSwUMPNektbtJqEjYZ6IRBqhqvJu1hKPYn9HYd75c0\ngIDYHJ9lb7QwQvg44aO27104rDK0xSstzL0CAwEAAQJAe5z5096oyeqGX6J+RGGx\n11yuDJ7J+0N4tthUHSWWUtgkd19NvmTM/mVLmPCzZHgNUT+aWUKsQ84+jhru/NQD\n0QIhAOHOzFmjxjTAR1jspn6YtJBKQB40tvT6WEvm2mKm0aD7AiEAyRPwXyZf3JT+\nM6Ui0Mubs7Qb/E4g1d/kVL+o/XoZC6cCIQC+nKzPtnooKW+Q1yOslgdGDgeV9/XB\nUlqap+MNh7hJZQIgZNaM+wqhlFtbx8aO2SrioJI4XqVHrjojpaSgOM3cdY0CIQDB\nQ6ckOaDV937acmWuiZhxuG2euNLwNbMldtCV5ADo/g==\n-----END RSA PRIVATE KEY-----'
    JWT_PUBLIC_KEY_RSA_BUILDLY: $'-----BEGIN PUBLIC KEY-----\nMFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALFc9NFZaOaSwUMPNektbtJqEjYZ6IRB\nqhqvJu1hKPYn9HYd75c0gIDYHJ9lb7QwQvg44aO27104rDK0xSstzL0CAwEAAQ==\n-----END PUBLIC KEY-----'
    SECRET_KEY: "nothing"
    OAUTH_CLIENT_ID: "vBn4KsOCthm7TWzMH0kVV0dXkUPJEtOQwaLu0eoC"
    OAUTH_CLIENT_SECRET: "0aYDOHUNAxK4MjbnYOHhfrKx8EzjKqN6GbB6IGyCgpT6pmQ5pEVJmH7mIEUJ"
    DOCKER_REPO: "buildly/buildly"
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push "$DOCKER_REPO:$TRAVIS_TAG"
  on:
    branch: master
    tags: true